// <auto-generated />
using InheritanceExample.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InheritanceExample.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InheritanceExample.Modules.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("InheritanceExample.Modules.FullTimeEmployee", b =>
                {
                    b.HasBaseType("InheritanceExample.Modules.Employee");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.ToTable("FullTimeEmployees", (string)null);
                });

            modelBuilder.Entity("InheritanceExample.Modules.PartTimeEmployee", b =>
                {
                    b.HasBaseType("InheritanceExample.Modules.Employee");

                    b.Property<double>("HourRate")
                        .HasColumnType("float");

                    b.Property<int>("NumberOfHours")
                        .HasColumnType("int");

                    b.ToTable("PartTimeEmployees", (string)null);
                });

            modelBuilder.Entity("InheritanceExample.Modules.FullTimeEmployee", b =>
                {
                    b.HasOne("InheritanceExample.Modules.Employee", null)
                        .WithOne()
                        .HasForeignKey("InheritanceExample.Modules.FullTimeEmployee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InheritanceExample.Modules.PartTimeEmployee", b =>
                {
                    b.HasOne("InheritanceExample.Modules.Employee", null)
                        .WithOne()
                        .HasForeignKey("InheritanceExample.Modules.PartTimeEmployee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
